22-09-2016 , Version 2.11a InstallDir C:\ARCHIV~1\PyAfipWs1.18a C:\ARCHIV~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady
Linea de codigo de error: Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady
.Exepción: ResponseNotReady
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady

22-09-2016 , Version 2.11a InstallDir C:\ARCHIV~1\PyAfipWs1.18a C:\ARCHIV~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady
Linea de codigo de error: Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady
.Exepción: ResponseNotReady
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady

21-10-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
.Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
21-10-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
.Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
21-10-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
.Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
21-10-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
.Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
21-10-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,0)11000: Campo PtoVta, no es un punto de venta valido, los valores posibles son entre 1 y 99998
21-10-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,0)11000: Campo PtoVta, no es un punto de venta valido, los valores posibles son entre 1 y 99998
