07-12-2022 19:35:37 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 12544:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
12544:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
12544:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 12544:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
12544:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
12544:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 12544:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
12544:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
12544:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


07-12-2022 19:36:48 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 12544:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
12544:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
12544:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 12544:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
12544:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
12544:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 12544:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
12544:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
12544:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


07-12-2022 19:38:06 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)600: ValidacionDeToken: No aparecio CUIT en lista de relaciones: 30717405508
07-12-2022 19:42:04 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)600: ValidacionDeToken: No aparecio CUIT en lista de relaciones: 30717405508
07-12-2022 19:45:18 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)600: ValidacionDeToken: No aparecio CUIT en lista de relaciones: 30717405508
07-12-2022 19:45:45 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)600: ValidacionDeToken: No aparecio CUIT en lista de relaciones: 30717405508
07-12-2022 19:50:31 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)600: ValidacionDeToken: No aparecio CUIT en lista de relaciones: 30717405508
07-12-2022 19:53:52 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,5)600: ValidacionDeToken: No aparecio CUIT en lista de relaciones: 30717405508
19-09-2023 11:08:15 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\GMSOLU~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
.Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
01-12-2023 10:00:21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\GMSOLU~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfe_30717502740WSFE Version 1.23b WSFE InstallDir C:\GMSOLU~1\PyAfipWsEnviando TAConectando al servicio WSFEConexion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)600: ValidacionDeToken: No aparecio CUIT en lista de relaciones: 30717502740
01-12-2023 11:44:16 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\GMSOLU~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\GMSOLU~1\PyAfipWsEnviando TAConectando al servicio WSFEConexion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,3,1)Fecha Ulti: 01-12-2023Llamada: WSFE.CompConsultar602: No existen datos en nuestros registros para los parametros ingresados.
01-12-2023 11:47:50 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\GMSOLU~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\GMSOLU~1\PyAfipWsEnviando TAConectando al servicio WSFEConexion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,3,1)Fecha Ulti: 01-12-2023Llamada: WSFE.CompConsultar602: No existen datos en nuestros registros para los parametros ingresados.
01-12-2023 12:04:29 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\GMSOLU~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\GMSOLU~1\PyAfipWsEnviando TAConectando al servicio WSFEConexion ExistosaCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: WSFE.Dummy()Procedimiento: sw_wsfe_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)
.Exepción: AttributeError: Tag not found: Body (No elements found)
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)

01-12-2023 12:04:33 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\GMSOLU~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\GMSOLU~1\PyAfipWsEnviando TAConectando al servicio WSFEConexion ExistosaCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: WSFE.Dummy()Procedimiento: sw_wsfe_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)
.Exepción: AttributeError: Tag not found: Body (No elements found)
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)

01-12-2023 12:06:48 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\GMSOLU~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\GMSOLU~1\PyAfipWsEnviando TAConectando al servicio WSFEConexion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,3,1)Fecha Ulti: 01-12-2023ERROR AL SOLICITARCAEEl nro de comprobante autorizado 1 ya se encontraba informado.El ultimo autorizado por Afip es 1El CUIT consultado (30229993)no coincide con el del comprobante (0)
01-12-2023 12:10:42 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\GMSOLU~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\GMSOLU~1\PyAfipWsEnviando TAConectando al servicio WSFEConexion ExistosaCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: WSFE.Dummy()Procedimiento: sw_wsfe_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)
.Exepción: AttributeError: Tag not found: Body (No elements found)
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)

01-12-2023 12:10:59 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\GMSOLU~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\GMSOLU~1\PyAfipWsEnviando TAConectando al servicio WSFEConexion ExistosaCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: WSFE.Dummy()Procedimiento: sw_wsfe_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)
.Exepción: AttributeError: Tag not found: Body (No elements found)
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)

01-12-2023 12:11:16 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\GMSOLU~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\GMSOLU~1\PyAfipWsEnviando TAConectando al servicio WSFEConexion ExistosaCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: WSFE.Dummy()Procedimiento: sw_wsfe_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)
.Exepción: AttributeError: Tag not found: Body (No elements found)
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)

01-12-2023 12:11:33 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\GMSOLU~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\GMSOLU~1\PyAfipWsEnviando TAConectando al servicio WSFEConexion ExistosaCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: WSFE.Dummy()Procedimiento: sw_wsfe_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)
.Exepción: AttributeError: Tag not found: Body (No elements found)
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)

01-12-2023 12:15:31 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\GMSOLU~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\GMSOLU~1\PyAfipWsEnviando TAConectando al servicio WSFEConexion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,3,1)Fecha Ulti: 01-12-2023ERROR AL SOLICITARCAEEl nro de comprobante autorizado 1 ya se encontraba informado.El ultimo autorizado por Afip es 1El CUIT consultado (30229993)no coincide con el del comprobante (0)
