06-04-2019 , soap:Server: No se pudo verificar que <sign> contenga una firma valida de <token>Error number: 1429Error message: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  FiLine of code with error: ok = PADRON.Consultar(cDocumento)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , soap:Server: No se pudo verificar que <sign> contenga una firma valida de <token>Error number: 12Error message: No se encuentra la variable 'OK'.Line of code with error: IF okLine number of error: 80Program with error: ERRHAND3
06-04-2019 , soap:Server: No se pudo verificar que <sign> contenga una firma valida de <token>Error number: 11Error message: El valor, tipo o número de argumentos no es válido para la función.Line of code with error: lok = MESSAGEBOX(lcmensaje,lnopcion,'INFORMACION AL USUARIO',ntimeout)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , soap:Server: No se pudo verificar que <sign> contenga una firma valida de <token>Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: oavisar.usuario("Tipo:",+ padron.tipo_persona+ " " + padron.tipo_doc + " " + padron.dni)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , soap:Server: No se pudo verificar que <sign> contenga una firma valida de <token>Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: oavisar.usuario("Impuestos:"+ padron.impuestos)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , soap:Server: No se pudo verificar que <sign> contenga una firma valida de <token>Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: oavisar.usuario("Actividades:"+ padron.actividades)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , soap:Server: No se pudo verificar que <sign> contenga una firma valida de <token>Error number: 1426Error message: Código de error OLE 0x80020006: Código de estado de COM desconocido.Line of code with error: oavisar.usuario("Errores:"+ padron.errores)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 1429Error message: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  FiLine of code with error: ok = PADRON.Consultar(cDocumento)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 12Error message: No se encuentra la variable 'OK'.Line of code with error: IF okLine number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 11Error message: El valor, tipo o número de argumentos no es válido para la función.Line of code with error: lok = MESSAGEBOX(lcmensaje,lnopcion,'INFORMACION AL USUARIO',ntimeout)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: oavisar.usuario("Tipo:",+ padron.tipo_persona+ " " + padron.tipo_doc + " " + padron.dni)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: oavisar.usuario("Impuestos:"+ padron.impuestos)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: oavisar.usuario("Actividades:"+ padron.actividades)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 1426Error message: Código de error OLE 0x80020006: Código de estado de COM desconocido.Line of code with error: oavisar.usuario("Errores:"+ padron.errores)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 1429Error message: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  FiLine of code with error: ok = PADRON.Consultar(cDocumento)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 12Error message: No se encuentra la variable 'OK'.Line of code with error: IF okLine number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 11Error message: El valor, tipo o número de argumentos no es válido para la función.Line of code with error: lok = MESSAGEBOX(lcmensaje,lnopcion,'INFORMACION AL USUARIO',ntimeout)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: oavisar.usuario("Tipo:",+ padron.tipo_persona+ " " + padron.tipo_doc + " " + padron.dni)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: oavisar.usuario("Impuestos:"+ padron.impuestos)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: oavisar.usuario("Actividades:"+ padron.actividades)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , AttributeError: 'NoneType' object has no attribute 'getPersona'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 194, in Consultar
AttributeError: 'NoneType' object has no attribute 'getPersona'
Error number: 1426Error message: Código de error OLE 0x80020006: Código de estado de COM desconocido.Line of code with error: oavisar.usuario("Errores:"+ padron.errores)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 1429Error message: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  FiLine of code with error: ok = PADRON.Consultar(cDocumento)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 12Error message: No se encuentra la variable 'OK'.Line of code with error: IF okLine number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 11Error message: El valor, tipo o número de argumentos no es válido para la función.Line of code with error: lok = MESSAGEBOX(lcmensaje,lnopcion,'INFORMACION AL USUARIO',ntimeout)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: oavisar.usuario("Tipo:",+ padron.tipo_persona+ " " + padron.tipo_doc + " " + padron.dni)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: oavisar.usuario("Impuestos:"+ padron.impuestos)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: oavisar.usuario("Actividades:"+ padron.actividades)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 1426Error message: Código de error OLE 0x80020006: Código de estado de COM desconocido.Line of code with error: oavisar.usuario("Errores:"+ padron.errores)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 1429Error message: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  FiLine of code with error: ok = PADRON.Consultar(cDocumento)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 12Error message: No se encuentra la variable 'OK'.Line of code with error: IF okLine number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 94Error message: Debe especificar parámetros adicionales.Line of code with error: LPARAMETERS cMensajeLine number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: This.GetTraza("Tipo:",+ padron.tipo_persona+ " " + padron.tipo_doc + " " + padron.dni)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: This.GetTraza("Impuestos:"+ padron.impuestos)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: This.GetTraza("Actividades:"+ padron.actividades)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 1426Error message: Código de error OLE 0x80020006: Código de estado de COM desconocido.Line of code with error: This.GetTraza("Errores:"+ padron.errores)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 1429Error message: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  FiLine of code with error: ok = PADRON.Consultar(cDocumento)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 12Error message: No se encuentra la variable 'OK'.Line of code with error: IF okLine number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 94Error message: Debe especificar parámetros adicionales.Line of code with error: LPARAMETERS cMensajeLine number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: This.GetTraza("Tipo:",+ padron.tipo_persona+ " " + padron.tipo_doc + " " + padron.dni)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: This.GetTraza("Impuestos:"+ padron.impuestos)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: This.GetTraza("Actividades:"+ padron.actividades)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 1426Error message: Código de error OLE 0x80020006: Código de estado de COM desconocido.Line of code with error: This.GetTraza("Errores:"+ padron.errores)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 1429Error message: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  FiLine of code with error: ok = PADRON.Consultar(cDocumento)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 12Error message: No se encuentra la variable 'OK'.Line of code with error: IF okLine number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 94Error message: Debe especificar parámetros adicionales.Line of code with error: LPARAMETERS cMensajeLine number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: This.GetTraza("Tipo:",+ padron.tipo_persona+ " " + padron.tipo_doc + " " + padron.dni)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: This.GetTraza("Impuestos:"+ padron.impuestos)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: This.GetTraza("Actividades:"+ padron.actividades)Line number of error: 80Program with error: ERRHAND3
06-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 1426Error message: Código de error OLE 0x80020006: Código de estado de COM desconocido.Line of code with error: This.GetTraza("Errores:"+ padron.errores)Line number of error: 80Program with error: ERRHAND3
09-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 1429Error message: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  FiLine of code with error: ok = PADRON.Consultar(cDocumento)Line number of error: 80Program with error: ERRHAND3
09-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 12Error message: No se encuentra la variable 'OK'.Line of code with error: IF okLine number of error: 80Program with error: ERRHAND3
09-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 94Error message: Debe especificar parámetros adicionales.Line of code with error: LPARAMETERS cMensajeLine number of error: 80Program with error: ERRHAND3
09-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: This.GetTraza("Tipo:",+ padron.tipo_persona+ " " + padron.tipo_doc + " " + padron.dni)Line number of error: 80Program with error: ERRHAND3
09-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: This.GetTraza("Impuestos:"+ padron.impuestos)Line number of error: 80Program with error: ERRHAND3
09-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 107Error message: Incompatibilidad entre el tipo de operador y el tipo de operando.Line of code with error: This.GetTraza("Actividades:"+ padron.actividades)Line number of error: 80Program with error: ERRHAND3
09-04-2019 , KeyError: 'idImpuesto'
Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 244, in Consultar
KeyError: 'idImpuesto'
Error number: 1426Error message: Código de error OLE 0x80020006: Código de estado de COM desconocido.Line of code with error: This.GetTraza("Errores:"+ padron.errores)Line number of error: 80Program with error: ERRHAND3
