22-03-2022 17:34:39 , REGFACVTA.INIT, Error: La sesión de datos nº 4 no se puede liberar si hay transacciones abiertas.;Linea : lObjeto = CREATEOBJECT("Custom");Error :       1549;Ultimo Alias Activo: ;Ultimo registro:          0 ;DBF: ;Ultimo Control activo: 
22-03-2022 17:34:39 , Pila de llamadas
22-03-2022 17:34:39 , Programa    : j:\xsoftsql\proyectos\hernan\forms\regfacvta.sct
22-03-2022 17:34:39 , Objeto      : regfacvta.init
22-03-2022 17:34:39 , Base Objeto : j:\xsoftsql\proyectos\hernan\forms\regfacvta.sct
22-03-2022 17:34:39 , Nº de Linea :         38
22-03-2022 17:34:39 , En el Fuente: 	.leerconfigbalanza(@oConfigBalanza,1)
22-03-2022 17:34:39 , Programa    : j:\xsoftsql\proyectos\hernan\forms\regfacvta.sct
22-03-2022 17:34:39 , Objeto      : regfacvta.leerconfigbalanza
22-03-2022 17:34:39 , Base Objeto : j:\xsoftsql\proyectos\hernan\forms\regfacvta.sct
22-03-2022 17:34:39 , Nº de Linea :          4
22-03-2022 17:34:39 , En el Fuente: 	lObjeto = CREATEOBJECT("Custom")
22-03-2022 17:34:39 , Fin
