27-03-2020 13:04:43 , PIDOLISTCTACTE.INIT, Error: La referencia al subíndice no es válida.;Linea : aListados[1,1]	= 'Resumen';Error :         31;Ultimo Alias Activo: CSRSETEO;Ultimo registro:          1 ;DBF: C:\USERS\MARCO\APPDATA\LOCAL\TEMP\0000B9XL04J4.TMP;Ultimo Control activo: 
27-03-2020 13:04:43 , Pila de llamadas
27-03-2020 13:04:43 , Programa    : j:\xsoftsql\proyectos\comercial\forms\ventas\pidolistctacte.sct
27-03-2020 13:04:43 , Objeto      : pidolistctacte.init
27-03-2020 13:04:43 , Base Objeto : j:\xsoftsql\proyectos\comercial\forms\ventas\pidolistctacte.sct
27-03-2020 13:04:43 , Nº de Linea :         11
27-03-2020 13:04:43 , En el Fuente: aListados[1,1]	= 'Resumen'
27-03-2020 13:04:43 , Fin
