22-09-2016 , Version 2.11a InstallDir C:\ARCHIV~1\PyAfipWs1.18a C:\ARCHIV~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady
Linea de codigo de error: Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady
.Exepción: ResponseNotReady
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady

22-09-2016 , Version 2.11a InstallDir C:\ARCHIV~1\PyAfipWs1.18a C:\ARCHIV~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady
Linea de codigo de error: Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady
.Exepción: ResponseNotReady
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady

26-05-2017 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 255, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
.Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
27-09-2017 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(0,0)11000: Campo PtoVta, no es un punto de venta valido, los valores posibles son entre 1 y 9998
11001: Campo CbteTipo, no es un tipo de comprobante valido. Ver metodo FEParamGetTiposCbte
27-09-2017 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(0,0)11000: Campo PtoVta, no es un punto de venta valido, los valores posibles son entre 1 y 9998
11001: Campo CbteTipo, no es un tipo de comprobante valido. Ver metodo FEParamGetTiposCbte
